[build]
  publish = "." # keep if your site root is the publish dir; change if needed
  command = "echo 'Static site — no build step'"
  functions = "netlify/functions"

[context.production.environment]
  SECRETS_SCAN_ENABLED = "false"
