[build]
publish = "dist" # or whatever your publish directory is
command = "echo 'Static site — no build step'" # or your build command

[context.production.environment]
SECRETS_SCAN_ENABLED = "false"