[build]
  publish = "."       # root publish for static site (adjust if your built files are in 'dist' or 'public')
  functions = "netlify/functions"

[dev]
  command = "netlify dev"
  port = 8888


[build.environment]
SECRETS_SCAN_OMIT_PATHS = "netlify/functions/capture-paypal-order.js netlify/functions/create-paypal-order.js netlify/functions/get-paypal-order.js"ß